config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'leagues#index'
  resources :leagues, only: %i[index show]
  resources :teams, only: %i[index show]
  resources :players, only: %i[index show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :participant
  belongs_to :team

  scope :active, -> { where(end_date: nil) }
  scope :not_active, -> { where('end_date != ?', nil) }

  as_enum :position, player: 0, coach: 1
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
  has_many :leagues
  has_many :players
end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams
  belongs_to :country
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_many :contracts
  has_many :teams, through: :contracts
  has_one :player
  belongs_to :country
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :participant

  as_enum :position, goalkeeper: 0, defender: 1, midfielder: 2, attaker: 3

  def age
    Time.current.year - participant.date_of_birth.year
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :contracts
  has_many :participants, through: :contracts
  has_many :players, through: :participants
  belongs_to :city
  belongs_to :league
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: :show

  def index
    @leagues = League.all
  end

  def show; end

  private

  def set_league
    @league = League.find(params[:id])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: :show

  def index
    @players = Player.page(params[:page])
  end

  def show; end

  private

  def set_player
    @player = Player.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: :show

  def index
    @teams = Team.all
  end

  def show; end

  private

  def set_team
    @team = Team.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Leagues
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/leagues/index.html.slim
h1 Leagues

table
  thead
    tr
      th
      th Name
      th Team size
      th Country
  tbody
    - @leagues.each do |league|
      tr
        td
          = link_to league
            = league.id
        td = league.name
        td = league.team_size
        td = league.country.name

app/views/leagues/show.html.slim
table
  tr
    th Name
    td = @league.name
  tr
    th League
    td = @league.team_size
  tr
    th City
    td = @league.country.name

= link_to 'back', leagues_path

app/views/players/index.html.slim
h1 Players

table
  thead
    tr
      th
      th First name
      th Last name
      th Age
      th Country
      th Talent
      th Position
      th Team
  tbody
    - @players.each do |player|
      tr
        td
          = link_to player
            = player.id
        td = player.participant.first_name
        td = player.participant.last_name
        td = player.age
        td = player.participant.country.name
        td = player.talent
        td = player.position
        td = player.participant.teams.last.name

= paginate @players

app/views/players/show.html.slim
table
  tr
    th First name
    td = @player.participant.first_name
  tr
    th Last name
    td = @player.participant.last_name
  tr
    th Age
    td = @player.age
  tr
    th Country
    td = @player.participant.country.name
  tr
    th Talent
    td = @player.talent
  tr
    th Position
    td = @player.position
  tr
    th Team
    td = @player.participant.teams.last.name

= link_to 'back', players_path